server:
  port: ${PORT:8004}

spring:
  application:
    name: inventory-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: inventory
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck:
      enabled: true